services:
  rstudio:
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      - TZ=Asia/Tokyo
      - DISABLE_AUTH=true
    volumes:
      - ..:/home/rstudio/${LOCAL_WORKSPACE_FOLDER_BASENAME}
      - renv:/home/rstudio/.cache/R/renv
      - pip:/home/rstudio/.cache/pip
      - julia:/home/rstudio/.julia
      - TinyTeX:/home/rstudio/.TinyTeX
      - fonts:/usr/share/fonts
      - pydrive2fs:/home/rstudio/.cache/pydrive2fs
volumes:
  renv:
    external: true
  pip:
    external: true
  julia:
    external: true
  TinyTeX:
    external: true
  fonts:
    external: true
  pydrive2fs:
    external: true
